//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyRestaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPLEADOS
    {
        public int ID_EMPLEADO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public int ID_SUCURSAL { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
        public decimal SALARIO { get; set; }
        public int TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public string TIEMPO_SERVICIO { get; set; }
        public string TIPO_USUARIO { get; set; }
    }
}
