//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyRestaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PROVEEDORES
    {
        public int ID_PROVEEDOR { get; set; }
        public string PROVEEDOR { get; set; }
        public string NOMBRE_CONTACTO { get; set; }
        public int TELEFONO { get; set; }
        public string SITIO_WEB { get; set; }
    }
}
