//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyRestaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INVENTARIO
    {
        public int ID_INVENTARIO { get; set; }
        public string INGREDIENTE { get; set; }
        public System.DateTime VENCIMIENTO { get; set; }
        public string MARCA { get; set; }
        public int ID_PROVEEDOR { get; set; }
    }
}
